functions:
  web:
    lang: node10-express
    handler: ./ts-frontend
    image: qolzam/web:0.16
    fprocess: ""
    environment:
      base_href: /function/web/
      gateway_url: http://faas.example.com:31112/function
      query_pretty_url: "true"
      websocket_url: http://social.example.com:3001
      write_debug: "true"
    labels:
      com.openfaas.scale.zero: "false"
      openfaas-cloud: "1"
      role: openfaas-system
      telar.dev.appID: my-social-network
      telar.dev.repo: ts-ui
    annotations:
      linkerd.io/inject: disabled
provider:
  name: openfaas
  gateway: http://192.168.1.18:31112
