provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  web:
    lang: node10-express
    handler: ./ts-frontend
    image: qolzam/web:0.4.5
    annotations:
      linkerd.io/inject: disabled
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      gateway_url: https://red-gold.o6s.io
      base_href: '/web/'
      websocket_url: "wss://red-gold-socket.herokuapp.com"
      query_pretty_url: true